### ISSUE TITLE
(7) level 6, Kinesis Agent not starting

### ISSUE THREAD

**Issue by lsida** [qyjohn/web-demo#1]
Hi John,

When I follow the wiki doing (7) level 6, it worked all good on one ec3 instance. However after I create a new AMI from the working instance, and then create a new launch configuration to edit the autoscaling group, the new instance launched by autoscaling group cannot send logs to Kinesis. I ssh into the new ec2 instance, and found that the kinesis-agent was exit, and the error is

- Failed to create or connect to the checkpoint database

I googled the error and found a discussion here
https://github.com/awslabs/amazon-kinesis-agent/issues/39

I followed the suggestion, and it solved the problem.

Just let you know this issue, and please ignore if you do it on purpose and leave it to us for troubleshooting.

Thanks,
Sida

**Comment by qyjohn** [comment]
Thank you very much for the feedback. You are right this is part of the trouble shooting problem "designed" in this tutorial. I am glad that you have arrived at this step, and thankful for you making the effort to raise an issue. Really appreciate that!
