### ISSUE TITLE
RDS Master Username Update

### ISSUE THREAD

**Issue by nicholasnelson** [qyjohn/web-demo#2]
In Level 1, Step 3:
`$ mysql -h [endpoint-of-rds-instance] -u root -p`

The default master username of a MySQL RDS instance is "admin", not "root".

Suggest updating this step to either specify to change the default master username in the create step, or use the correct default in the connect step.

**Comment by qyjohn** [comment]
Thank you. Added a note regarding the default username in the wiki page.
