### ISSUE TITLE
Fix some typos

### ISSUE THREAD

**Issue by ttres** [qyjohn/web-demo#3]
I fixed some wiki typos and published the correction on my ow repository:

https://github.com/ttres/web-demo-wiki (git@github.com:ttres/web-demo-wiki.git)

The detailed changes are here:

https://github.com/ttres/web-demo-wiki/commit/718f2b488aa9e3846bd9466b0e930a33f6ab7541?diff=unified

Feel free to apply them if desired.

**Comment by qyjohn** [comment]
Thanks a lot. Fixed.
