### ISSUE TITLE
Remove $ symbol from each command  in wiki 

### ISSUE THREAD

**Issue by sivasankarig** [qyjohn/web-demo#4]
it would be helpful if  $ symbol removed before running command. I got below command when I clicked copy button. 

$ sudo apt-get install awscli apache2 
$ sudo apt-get install php libapache2-mod-php php-mysql php-curl php-xml php-memcached php-mbstring

**Comment by qyjohn** [comment]
This is intentional. Since this is a tutorial, we want people to read the commands, instead of simply copy and paste.

**Comment by sivasankarig** [comment]
okay! Makes Sense. Thanks!!
